#!/usr/bin/env python3

'''
    This script is to create a AXT file from a random sample of sequences to run pairwise dn/ds estimates using the kaks_calculator. 
    If you have a fasta file with multiple entries, then you want to use this script to create an axt file for pairwise dn/ds.
    This script was mean't to run on a fasta file generated with a random sequence of length X. The length has to be divisible by 3 or the kaks_calculator will return an error.
    If you have sequences of differing lengths, then using an aligner such as clustalw can help but another script would have to be implemented to create a AXT file for kaks_calculator input. 
'''

import argparse
import subprocess
import os
from Bio.SeqUtils.CheckSum import seguid
from Bio import SeqIO
from collections import defaultdict

def main(args):
    #use alignment fasta files
    o = open(args.output,'w')

    #does not for duplicate names checkout readme file
    seguid_dict = SeqIO.to_dict(SeqIO.parse(args.input_aln, "fasta"), lambda rec: seguid(rec.seq))

    def divisible_by_3(sequence):
        if len(sequence) % 3 != 0:
            if len(sequence+'-') % 3 != 0:
                return(sequence+'--')
            else:
                return(sequence+'-')
        else:
            return(sequence)

    for key1 in seguid_dict:
        ref = seguid_dict[key1].description
        ref_seq = str(seguid_dict[key1].seq)
        o.write('>'+ref)
        o.write('\n')
        o.write(divisible_by_3(ref_seq))
        o.write('\n')
    o.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description = 'Run KaKs_calculator on a random fasta file generated and simulated for testing ground truths'
    )

    parser.add_argument(
        '--input_aln',
        type=str,
        help = 'Input alignment file generated by clustalw'
    )

    parser.add_argument(
        '--output',
        type=str,
        help = 'Output name for modified file'
    )
    
    args = parser.parse_args()

    main(args)

